name: Test

on: push

jobs:
  test:
    name: "PHPUnit (PHP ${{ matrix.php }})"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php:
          - "7.4"
          - "8.0"
          - "8.1"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"

      - name: Install Composer dependencies
        run: composer update --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Tests
        run: composer run-script test
